
// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file was generated by plugin-generate-structured-data.
// To update, modify the source markdown files or the plugin configuration and re-run the generator.

import React from 'react';
import { useLocation } from '@docusaurus/router';

export default function Root({ children }) {
  const location = useLocation();

  const baseUrl = "https://horizonrepublic.github.io";
  const currentPath = location.pathname;
  const fullUrl = baseUrl + currentPath;
  const locales = ["en"];

    
  const mainI18nData = {
  "default": {
    "baseSchema": {
      "organization": {
        "@type": "Organization",
        "name": "Horizon Republic",
        "url": "https://horizonrepublic.github.io"
      }
    }
  }
};
  const homePathes = locales.map(locale => locale === 'en' ? '/' : '/' + locale + '/'); ;

  const schemas = {

    
    '/docs/development/contributing/': {
  "@type": "Article",
  "headline": "Contributing",
  "description": "How to contribute to the project.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-03-31"
},
      
    '/docs/development/testing/': {
  "@type": "Article",
  "headline": "Testing",
  "description": "Running unit and integration tests with Vitest and Testcontainers.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-03-31"
},
      
    '/docs/getting-started/installation/': {
  "@type": "Article",
  "headline": "Installation",
  "description": "Install the package, set up NATS with Docker, and configure peer dependencies.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-02"
},
      
    '/docs/getting-started/module-configuration/': {
  "@type": "Article",
  "headline": "Module Configuration",
  "description": "forRoot(), forRootAsync(), and forFeature() registration methods with stream, consumer, and connection options.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-02"
},
      
    '/docs/getting-started/quick-start/': {
  "@type": "Article",
  "headline": "Quick Start",
  "description": "Complete working example in four steps: register the module, connect the transport, define handlers, and send messages.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-03-21"
},
      
    '/docs/guides/custom-codec/': {
  "@type": "Article",
  "headline": "Custom Codec",
  "description": "Replace the default JSON codec with MsgPack, Protobuf, or any custom binary format.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-02"
},
      
    '/docs/guides/dead-letter-queue/': {
  "@type": "Article",
  "headline": "Dead Letter Queue",
  "description": "Handle messages that exhaust all delivery attempts via onDeadLetter callback.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-03-21"
},
      
    '/docs/guides/graceful-shutdown/': {
  "@type": "Article",
  "headline": "Graceful Shutdown",
  "description": "Automatic shutdown handling with in-flight message completion and NATS connection drain.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-02"
},
      
    '/docs/guides/handler-context/': {
  "@type": "Article",
  "headline": "Handler Context",
  "description": "Access message metadata, headers, and control settlement actions via RpcContext.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-03-30"
},
      
    '/docs/guides/health-checks/': {
  "@type": "Article",
  "headline": "Health Checks",
  "description": "JetstreamHealthIndicator for NestJS Terminus integration with connection status and latency.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-03-26"
},
      
    '/docs/guides/lifecycle-hooks/': {
  "@type": "Article",
  "headline": "Lifecycle Hooks",
  "description": "Transport lifecycle events for connection changes, errors, message routing, and dead letters.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-02"
},
      
    '/docs/guides/migration/': {
  "@type": "Article",
  "headline": "Migration Guide",
  "description": "Migrate from the built-in NestJS NATS transport to JetStream with durable delivery.",
  "datePublished": "2026-03-26",
  "dateModified": "2026-04-02"
},
      
    '/docs/guides/per-message-ttl/': {
  "@type": "Article",
  "headline": "Per-Message TTL",
  "description": "Individual message expiration independent of stream max_age, powered by NATS 2.11 Nats-TTL header.",
  "datePublished": "2026-04-02",
  "dateModified": "2026-04-02"
},
      
    '/docs/guides/performance/': {
  "@type": "Article",
  "headline": "Performance Tuning",
  "description": "Tune ackWait, maxAckPending, batch sizes, and ack extension for high-throughput workloads.",
  "datePublished": "2026-03-26",
  "dateModified": "2026-04-02"
},
      
    '/docs/guides/record-builder/': {
  "@type": "Article",
  "headline": "Record Builder & Deduplication",
  "description": "Build messages with custom headers, message IDs, and deduplication via JetstreamRecordBuilder.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-02"
},
      
    '/docs/guides/scheduling/': {
  "@type": "Article",
  "headline": "Scheduling (Delayed Jobs)",
  "description": "One-shot delayed message delivery powered by NATS 2.12 message scheduling.",
  "datePublished": "2026-04-01",
  "dateModified": "2026-04-01"
},
      
    '/docs/guides/stream-migration/': {
  "@type": "Article",
  "headline": "Stream Migration",
  "description": "Safe stream recreation for immutable property changes with automatic message preservation via blue-green sourcing.",
  "datePublished": "2026-04-02",
  "dateModified": "2026-04-02"
},
      
    '/docs/guides/troubleshooting/': {
  "@type": "Article",
  "headline": "Troubleshooting",
  "description": "Common issues and how to resolve them.",
  "datePublished": "2026-03-26",
  "dateModified": "2026-03-26"
},
      
    '/docs/': {
  "@type": "Article",
  "headline": "Introduction",
  "description": "Production-grade NestJS transport for NATS JetStream with durable delivery, retry, replay, and dead letter handling.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-01"
},
      
    '/docs/patterns/broadcast/': {
  "@type": "Article",
  "headline": "Broadcast Events",
  "description": "Fan-out event delivery to every subscribing service instance.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-02"
},
      
    '/docs/patterns/events/': {
  "@type": "Article",
  "headline": "Events (Workqueue)",
  "description": "Workqueue events with at-least-once delivery, automatic retry, deduplication, and dead letter handling.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-02"
},
      
    '/docs/patterns/handler-metadata/': {
  "@type": "Article",
  "headline": "Handler Metadata Registry",
  "description": "Publish handler metadata to a NATS KV bucket for dynamic service discovery, API gateway routing, and catalog generation.",
  "datePublished": "2026-04-02",
  "dateModified": "2026-04-03"
},
      
    '/docs/patterns/ordered-events/': {
  "@type": "Article",
  "headline": "Ordered Events",
  "description": "Strict sequential event delivery with ephemeral consumers and replay policies.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-02"
},
      
    '/docs/patterns/rpc/': {
  "@type": "Article",
  "headline": "RPC (Request/Reply)",
  "description": "Synchronous request-reply via Core NATS or JetStream with timeout and error handling.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-03-26"
},
      
    '/docs/reference/default-configs/': {
  "@type": "Article",
  "headline": "Default Configs",
  "description": "Default stream and consumer configurations for every StreamKind.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-02"
},
      
    '/docs/reference/edge-cases/': {
  "@type": "Article",
  "headline": "Edge Cases & FAQ",
  "description": "Common questions and non-obvious behaviors of the transport.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-02"
},
      
    '/docs/reference/naming-conventions/': {
  "@type": "Article",
  "headline": "Naming Conventions",
  "description": "Stream, consumer, and subject naming patterns derived from the service name.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-02"
},
      

  };
  for (const homePath of homePathes) {
    schemas[homePath] = { "@type": "WebSite", "name": "@horizon-republic/nestjs-jetstream", "description": "Production-grade NestJS transport for NATS JetStream — events, broadcast, ordered delivery, and RPC." };
  }
  
  // Get the schema for the current page
  // Normalize path: strip baseUrl prefix and match with/without trailing slash
  const siteBaseUrl = '/nestjs-jetstream';
  const strippedPath = location.pathname.startsWith(siteBaseUrl)
    ? location.pathname.slice(siteBaseUrl.length) || '/'
    : location.pathname;
  const contentData = schemas[strippedPath] || schemas[strippedPath + '/'] || schemas[strippedPath.replace(/\/$/, '')];
  if (contentData) {
    let isSupportedType = true;
    const schemaType = contentData['@type'];
    const articlesWithAuthorPublisher = ['Article', 'BlogPosting', 'CollectionPage', 'Blog', 'AboutPage'];
    const servicesWithProvider = ['Service', 'WebSite'];

    if (articlesWithAuthorPublisher.includes(schemaType)) {
      contentData.author = {
        '@id': `${baseUrl}/#person`
      };
      contentData.publisher = {
        '@id': `${baseUrl}/#organization`
      };
    } else if (servicesWithProvider.includes(schemaType)) {
      contentData.provider = {
        '@id': `${baseUrl}/#organization`
      };
    } else if (schemaType === 'Organization' || schemaType === 'Person') {
      // No automatic enrichment for these types
    } else {
      isSupportedType = false;
      console.warn(`No schema.org handling for type: ${schemaType} on path: ${location.pathname}`);
    }

    if (isSupportedType) {
        contentData.url = fullUrl;
        contentData.mainEntityOfPage = {
        '@type': 'WebPage',
        '@id': `${fullUrl}#webpage`
        };
    }
  }

  // Build the full graph
  let graphData = null;
  const key = location.pathname.split('/')[1];
  let selectedPersonData = null;
  let selectedOrgData = null;
  let selectedWebsiteData = null;
  let currentLocale;
  if (locales.includes(key) && mainI18nData[key]) {
    currentLocale = key;
    // localized data
    selectedPersonData = mainI18nData[key].baseSchema ? mainI18nData[key].baseSchema.person : null;
    selectedOrgData = mainI18nData[key].baseSchema ? mainI18nData[key].baseSchema.organization : null;
    selectedWebsiteData = mainI18nData[key].baseSchema ? mainI18nData[key].baseSchema.website : null;
  }
  else {
    // default data
    selectedPersonData = mainI18nData['default'].baseSchema.person;
    selectedOrgData = mainI18nData['default'].baseSchema.organization;
    selectedWebsiteData = mainI18nData['default'].baseSchema.website;
  }

    // webpage data
    const webPageData = {
      '@type': 'WebPage',
      '@id': `${fullUrl}#webpage`,
      url: fullUrl,
      name: contentData && contentData.headline ? contentData.headline : '@horizon-republic/nestjs-jetstream',
      description: contentData && contentData.description ? contentData.description : undefined,
      inLanguage: currentLocale || 'en-US',
      isPartOf: {
        '@id': `${baseUrl}/#website`
      },
      author: contentData ? contentData.author : undefined,
      publisher: contentData ? contentData.publisher : undefined,
      provider: contentData ? contentData.provider : undefined
    };

    const graphContent = [];
    if (selectedOrgData) {
      graphContent.push(selectedOrgData);
    }
    if (selectedPersonData) {
      graphContent.push(selectedPersonData);
    }
    if (selectedWebsiteData) {
      graphContent.push(selectedWebsiteData);
    }
    graphContent.push(webPageData);

    if (contentData) {
        if (Object.keys(contentData).length > 0) {
            graphContent.push(contentData);
        }
    }
    else {
        console.warn(`No schema.org data for path: ${location.pathname}`);
    }

    graphData = {
      '@context': 'https://schema.org',
      '@graph': graphContent
    };

  return (
    <>
      {children}
      <script type="application/ld+json">
          {JSON.stringify(graphData)}
        </script>
    </>
  );
}
  