
// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file was generated by plugin-generate-structured-data.
// To update, modify the source markdown files or the plugin configuration and re-run the generator.

import React from 'react';
import { useLocation } from '@docusaurus/router';

export default function Root({ children }) {
  const location = useLocation();

  const baseUrl = "https://nestjs-jetstream.horizon-republic.dev";
  const currentPath = location.pathname;
  const fullUrl = baseUrl + currentPath;
  const locales = ["en"];

    
  const mainI18nData = {
  "default": {
    "baseSchema": {
      "organization": {
        "@type": "Organization",
        "name": "Horizon Republic",
        "url": "https://nestjs-jetstream.horizon-republic.dev"
      }
    }
  }
};
  const homePathes = locales.map(locale => locale === 'en' ? '/' : '/' + locale + '/'); ;

  const schemas = {

    
    '/docs/development/contributing/': {
  "@type": "Article",
  "headline": "Contributing",
  "description": "How to contribute to the project.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-11"
},
      
    '/docs/development/testing/': {
  "@type": "Article",
  "headline": "Testing",
  "description": "Running unit and integration tests with Vitest and Testcontainers.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-11"
},
      
    '/docs/getting-started/installation/': {
  "@type": "Article",
  "headline": "Installation",
  "description": "Install the package, set up NATS with Docker, and configure peer dependencies.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-11"
},
      
    '/docs/getting-started/quick-start/': {
  "@type": "Article",
  "headline": "Quick Start",
  "description": "Complete working example in four steps: register the module, connect the transport, define handlers, and send messages.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-11"
},
      
    '/docs/getting-started/why-jetstream/': {
  "@type": "Article",
  "headline": "Why JetStream? NestJS NATS Transport Comparison",
  "description": "When the built-in NestJS NATS transport is enough, and when your system outgrows Core NATS and needs JetStream for durable messaging.",
  "datePublished": "2026-04-11",
  "dateModified": "2026-04-11"
},
      
    '/docs/guides/custom-codec/': {
  "@type": "Article",
  "headline": "How to use a custom codec with NestJS JetStream",
  "description": "Replace JSON with MessagePack, Protobuf, or a custom binary codec for NATS message serialization.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-05-27"
},
      
    '/docs/guides/dead-letter-queue/': {
  "@type": "Article",
  "headline": "How to configure a Dead Letter Queue",
  "description": "Capture NestJS NATS JetStream messages that exhaust all delivery attempts via a DLQ stream or onDeadLetter callback.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-05-27"
},
      
    '/docs/guides/graceful-shutdown/': {
  "@type": "Article",
  "headline": "Graceful Shutdown",
  "description": "Automatic shutdown handling with in-flight message completion and NATS connection drain.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-11"
},
      
    '/docs/guides/handler-context/': {
  "@type": "Article",
  "headline": "RpcContext — Handler Context & Message Settlement",
  "description": "Access JetStream metadata and control ack, retry, and terminate actions in NestJS message handlers via RpcContext.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-11"
},
      
    '/docs/guides/health-checks/': {
  "@type": "Article",
  "headline": "How to expose health checks for NATS JetStream",
  "description": "Expose NATS connection status and RTT latency as a Kubernetes readiness/liveness probe using JetstreamHealthIndicator.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-05-27"
},
      
    '/docs/guides/lifecycle-hooks/': {
  "@type": "Article",
  "headline": "How to register lifecycle hooks for NestJS JetStream",
  "description": "Subscribe to transport events for monitoring, alerting, and logging integration.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-05-27"
},
      
    '/docs/guides/migration/': {
  "@type": "Article",
  "headline": "How to migrate from @nestjs/microservices NATS to JetStream",
  "description": "Step-by-step migration from the built-in NestJS NATS transport to durable JetStream-backed delivery.",
  "datePublished": "2026-03-26",
  "dateModified": "2026-05-27"
},
      
    '/docs/guides/per-message-ttl/': {
  "@type": "Article",
  "headline": "How to set per-message TTL on NATS JetStream messages",
  "description": "Set individual message expiration via the Nats-TTL header (NATS 2.11, ADR-43).",
  "datePublished": "2026-04-02",
  "dateModified": "2026-05-27"
},
      
    '/docs/guides/performance/': {
  "@type": "Article",
  "headline": "Performance Tuning",
  "description": "Tune ackWait, maxAckPending, batch sizes, and ack extension for high-throughput workloads.",
  "datePublished": "2026-03-26",
  "dateModified": "2026-04-11"
},
      
    '/docs/guides/record-builder/': {
  "@type": "Article",
  "headline": "JetstreamRecordBuilder — Headers, Message IDs & Deduplication",
  "description": "Build NestJS NATS messages with custom headers, deterministic message IDs for publish-side deduplication, and per-request RPC timeouts.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-11"
},
      
    '/docs/guides/scheduling/': {
  "@type": "Article",
  "headline": "How to schedule delayed messages with NestJS JetStream",
  "description": "One-shot delayed message delivery via the Nats-Schedule header (NATS 2.12, ADR-51).",
  "datePublished": "2026-04-01",
  "dateModified": "2026-05-27"
},
      
    '/docs/guides/stream-migration/': {
  "@type": "Article",
  "headline": "How to migrate immutable stream properties",
  "description": "Safely change immutable stream properties without losing messages via blue-green sourcing.",
  "datePublished": "2026-04-02",
  "dateModified": "2026-05-27"
},
      
    '/docs/guides/troubleshooting/': {
  "@type": "Article",
  "headline": "Troubleshooting — NestJS JetStream Transport",
  "description": "Fix common NestJS JetStream issues: NATS connection errors, consumer lag, RPC timeouts, DLQ publish failures, and stream migration recovery.",
  "datePublished": "2026-03-26",
  "dateModified": "2026-04-11"
},
      
    '/docs/': {
  "@type": "Article",
  "headline": "NestJS NATS Transport with JetStream — Introduction",
  "description": "A NestJS NATS microservice transport backed by JetStream: durable events, broadcast, ordered delivery, RPC, and dead letter queues.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-11"
},
      
    '/docs/observability/index/': {
  "@type": "Article",
  "headline": "Observability — NestJS JetStream Transport",
  "description": "Distributed tracing and Prometheus metrics built into the transport. Zero-config integration with OpenTelemetry SDKs and prom-client-based exporters.",
  "datePublished": "2026-05-27",
  "dateModified": "2026-05-27"
},
      
    '/docs/observability/metrics/': {
  "@type": "Article",
  "headline": "Prometheus Metrics — NestJS JetStream Transport",
  "description": "Production-ready Prometheus metrics for NATS JetStream transport: throughput, handler latency, consumer lag, dead letters, and publish errors.",
  "datePublished": "2026-05-27",
  "dateModified": "2026-05-27"
},
      
    '/docs/observability/tracing/': {
  "@type": "Article",
  "headline": "Distributed Tracing — NestJS JetStream Transport",
  "description": "Built-in W3C Trace Context propagation and OpenTelemetry spans for every publish, consume, and RPC round-trip.",
  "datePublished": "2026-04-24",
  "dateModified": "2026-05-27"
},
      
    '/docs/patterns/broadcast/': {
  "@type": "Article",
  "headline": "Broadcast Events — NestJS JetStream Fan-Out Delivery",
  "description": "Fan-out NATS JetStream events to every NestJS service instance via per-service durable consumers on a shared broadcast stream.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-11"
},
      
    '/docs/patterns/events/': {
  "@type": "Article",
  "headline": "Workqueue Events — NestJS JetStream At-Least-Once Delivery",
  "description": "NestJS NATS JetStream workqueue events with at-least-once delivery, automatic retry, publish-side deduplication, and dead letter handling.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-27"
},
      
    '/docs/patterns/handler-metadata/': {
  "@type": "Article",
  "headline": "Handler Metadata Registry — NATS KV Service Discovery for NestJS",
  "description": "Publish NestJS handler metadata to a NATS KV bucket for dynamic service discovery, API gateway routing, and automatic catalog generation.",
  "datePublished": "2026-04-02",
  "dateModified": "2026-04-11"
},
      
    '/docs/patterns/ordered-events/': {
  "@type": "Article",
  "headline": "Ordered Events — Strict Sequential Delivery in NATS JetStream",
  "description": "Strict sequential NestJS NATS JetStream event delivery with ephemeral ordered consumers, deliver policies, and CQRS replay patterns.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-11"
},
      
    '/docs/patterns/rpc/': {
  "@type": "Article",
  "headline": "NestJS NATS RPC — Core vs JetStream Request/Reply",
  "description": "Synchronous NestJS NATS request-reply in Core NATS or JetStream mode, with timeout handling, error serialization, and per-request overrides.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-11"
},
      
    '/docs/reference/default-configs/': {
  "@type": "Article",
  "headline": "Default Stream & Consumer Configs for NATS JetStream",
  "description": "Production-ready default stream, consumer, and connection settings for every NestJS JetStream StreamKind (event, broadcast, ordered, command, DLQ).",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-11"
},
      
    '/docs/reference/edge-cases/': {
  "@type": "Article",
  "headline": "Edge Cases & FAQ — NestJS JetStream Transport",
  "description": "NestJS JetStream transport FAQ: publisher-only mode, consumer self-healing, NATS header limits, fire-and-forget messaging, and DeliverPolicy edge cases.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-11"
},
      
    '/docs/reference/header-contract/': {
  "@type": "Article",
  "headline": "Header Contract — NATS Message Headers Used by the Transport",
  "description": "Stable contract for NATS message headers the transport reads and writes.",
  "datePublished": "2026-04-24",
  "dateModified": "2026-04-27"
},
      
    '/docs/reference/module-configuration/': {
  "@type": "Article",
  "headline": "Module Configuration Reference",
  "description": "Reference for forRoot(), forRootAsync(), and forFeature() registration methods with stream, consumer, and connection options.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-05-27"
},
      
    '/docs/reference/naming-conventions/': {
  "@type": "Article",
  "headline": "Naming Conventions",
  "description": "Stream, consumer, and subject naming patterns derived from the service name.",
  "datePublished": "2026-03-21",
  "dateModified": "2026-04-11"
},
      
    '/docs/reference/release-notes/': {
  "@type": "Article",
  "headline": "Release Notes — NestJS JetStream Transport",
  "description": "Version-by-version changelog covering new features, behavior changes, and breaking changes.",
  "datePublished": "2026-03-26",
  "dateModified": "2026-05-27"
},
      

  };
  for (const homePath of homePathes) {
    schemas[homePath] = { "@type": "WebSite", "name": "@horizon-republic/nestjs-jetstream", "description": "Production-grade NestJS transport for NATS JetStream — events, broadcast, ordered delivery, and RPC." };
  }
  
  // Get the schema for the current page
  // Normalize path: match with/without trailing slash
  const strippedPath = location.pathname || '/';
  const contentData = schemas[strippedPath] || schemas[strippedPath + '/'] || schemas[strippedPath.replace(/\/$/, '')];
  if (contentData) {
    let isSupportedType = true;
    const schemaType = contentData['@type'];
    const articlesWithAuthorPublisher = ['Article', 'BlogPosting', 'CollectionPage', 'Blog', 'AboutPage'];
    const servicesWithProvider = ['Service', 'WebSite'];

    if (articlesWithAuthorPublisher.includes(schemaType)) {
      contentData.author = {
        '@id': `${baseUrl}/#person`
      };
      contentData.publisher = {
        '@id': `${baseUrl}/#organization`
      };
    } else if (servicesWithProvider.includes(schemaType)) {
      contentData.provider = {
        '@id': `${baseUrl}/#organization`
      };
    } else if (schemaType === 'Organization' || schemaType === 'Person') {
      // No automatic enrichment for these types
    } else {
      isSupportedType = false;
      console.warn(`No schema.org handling for type: ${schemaType} on path: ${location.pathname}`);
    }

    if (isSupportedType) {
        contentData.url = fullUrl;
        contentData.mainEntityOfPage = {
        '@type': 'WebPage',
        '@id': `${fullUrl}#webpage`
        };
    }
  }

  // Build the full graph
  let graphData = null;
  const key = location.pathname.split('/')[1];
  let selectedPersonData = null;
  let selectedOrgData = null;
  let selectedWebsiteData = null;
  let currentLocale;
  if (locales.includes(key) && mainI18nData[key]) {
    currentLocale = key;
    // localized data
    selectedPersonData = mainI18nData[key].baseSchema ? mainI18nData[key].baseSchema.person : null;
    selectedOrgData = mainI18nData[key].baseSchema ? mainI18nData[key].baseSchema.organization : null;
    selectedWebsiteData = mainI18nData[key].baseSchema ? mainI18nData[key].baseSchema.website : null;
  }
  else {
    // default data
    selectedPersonData = mainI18nData['default'].baseSchema.person;
    selectedOrgData = mainI18nData['default'].baseSchema.organization;
    selectedWebsiteData = mainI18nData['default'].baseSchema.website;
  }

    // webpage data
    const webPageData = {
      '@type': 'WebPage',
      '@id': `${fullUrl}#webpage`,
      url: fullUrl,
      name: contentData && contentData.headline ? contentData.headline : '@horizon-republic/nestjs-jetstream',
      description: contentData && contentData.description ? contentData.description : undefined,
      inLanguage: currentLocale || 'en-US',
      isPartOf: {
        '@id': `${baseUrl}/#website`
      },
      author: contentData ? contentData.author : undefined,
      publisher: contentData ? contentData.publisher : undefined,
      provider: contentData ? contentData.provider : undefined
    };

    const graphContent = [];
    if (selectedOrgData) {
      graphContent.push(selectedOrgData);
    }
    if (selectedPersonData) {
      graphContent.push(selectedPersonData);
    }
    if (selectedWebsiteData) {
      graphContent.push(selectedWebsiteData);
    }
    graphContent.push(webPageData);

    if (contentData) {
        if (Object.keys(contentData).length > 0) {
            graphContent.push(contentData);
        }
    }
    else {
        console.warn(`No schema.org data for path: ${location.pathname}`);
    }

    graphData = {
      '@context': 'https://schema.org',
      '@graph': graphContent
    };

  return (
    <>
      {children}
      <script type="application/ld+json">
          {JSON.stringify(graphData)}
        </script>
    </>
  );
}
  